### ISSUE TITLE
approved application split

### ISSUE THREAD

**Issue by phac008** [suxess-it/sx-cnp-oss#108]
overlap of approved-application git repo when testing locally and running metal stack at the same time

think about a concept how to split this up in good solution
--
metalstack/k3d directory  vs fqdn directory vs ...

**Comment by phac008** [comment]
#115

**Comment by jkleinlercher** [comment]
in https://github.com/suxess-it/sx-cnp-oss/blob/gitops-strategies/proposals/gitops-structure.md I currently investigate in a  self-service app-onboarding approach without an "approved application" (document needs some restructure).

**Comment by jkleinlercher** [comment]
after https://github.com/suxess-it/sx-cnp-oss/issues/115 I think we do not need https://github.com/suxess-it/sx-cnp-oss/blob/main/platform-apps/charts/kargo/templates/approved-application.yaml, https://github.com/suxess-it/sx-cnp-oss/blob/main/platform-apps/charts/kubevirt/templates/approved-application.yaml and the git-repo https://github.com/suxess-it/approved-application.git anymore.

We should try the approach onboarding teams in https://github.com/suxess-it/sx-cnp-oss/blob/main/platform-apps/charts/team-onboarding/values-metalstack.yaml and https://github.com/suxess-it/sx-cnp-oss/blob/main/platform-apps/charts/team-onboarding/values-k3d.yaml . In those value-files we already have the possibility to have different teams in different clusters.

If we want to onboard the same teams in k3d and metalstack, we can seperate the applications based on the path in https://github.com/suxess-it/sx-cnp-oss/blob/5dc228968a8bb28c923558911698e7260399080b/platform-apps/charts/team-onboarding/values-metalstack.yaml#L15 

If we also want to collect different applications in the appset we define in https://github.com/suxess-it/sx-cnp-oss/blob/5dc228968a8bb28c923558911698e7260399080b/platform-apps/charts/team-onboarding/values-metalstack.yaml#L17 then we need to add some logic to the appset how to differentiate between those to targt. It could be some repository labels or the app-stages.yaml could have some target-prefix (e.g. k3d-app-stages.yaml and metalstack-app-stages.yaml)

**Comment by jkleinlercher** [comment]
@phac008 can we close this issue due to comment above?

**Comment by phac008** [comment]
@jkleinlercher lets try this. I will open a new issue to migrate backstage templates from approved applications to teams onboarding structure
