### ISSUE TITLE
Kargo should only be visible on Backstage Service Component Page if kargo annotation is set in catalog-info

### ISSUE THREAD

**Issue by phac008** [suxess-it/sx-cnp-oss#116]

**Comment by jkleinlercher** [comment]
all changes in https://github.com/suxess-it/sx-backstage/compare/32de267e72fca04d71c59152b9c2a2483cb2244e...8582b45c96348d1cbd00bfb8bc5287a890cdf8c1 solved this issue.

**Comment by jkleinlercher** [comment]
![image](https://github.com/suxess-it/sx-cnp-oss/assets/11465610/5bd30fbc-8d07-4207-bbde-4223f1d4b8fb)


![image](https://github.com/suxess-it/sx-cnp-oss/assets/11465610/6f67256d-f017-4dfe-a8e9-a6b08b4aa034)
