### ISSUE TITLE
[Template]Instantiate new Metalstack Cluster from sx-cnp portal

### ISSUE THREAD

**Issue by phac008** [suxess-it/sx-cnp-oss#165]

**Comment by jkleinlercher** [comment]
With Crossplane upjet we can create Crossplane provider out of terraform scripts and then metalstack cluster can get created from the mothership K8s cluster via ArgoCD app

**Comment by phac008** [comment]
demo now working with crossplane 
question left:
where to put cluster manifests - team-app onboarding structure for cluster too?
team-app for platform team - maybe a different approach will be better there?
