### ISSUE TITLE
[grafana] wrong "default" storage class 

### ISSUE THREAD

**Issue by phac008** [suxess-it/sx-cnp-oss#189]
https://github.com/suxess-it/sx-cnp-oss/commit/602120106416cbbc4ffbac2bed77d6c6908e690b

storageClassName: "local-path" not working in my environment - should refer to default storage class

**Comment by jkleinlercher** [comment]
should be fixed with https://github.com/suxess-it/sx-cnp-oss/commit/b36bce09792b39f7f07f02b49ba8caa9d9add9c7

**Comment by phac008** [comment]
ok now
