### ISSUE TITLE
[monitoring] servicemonitor

### ISSUE THREAD

**Issue by phac008** [suxess-it/sx-cnp-oss#424]
brick installation - if monitoring stack is deselected -> most installation will fail due to missing service monitor crd

**Comment by jkleinlercher** [comment]
The normal strategy for such cases would be to have a serviceMonitor.enabled flag in the values and/or use helm capabilities api to check if servicemonitor api is available.

**Comment by phac008** [comment]
ok, after bricks are defined we should think about best solution. 
for local development it's easiest for now to add crd apply to local deployment skript
