### ISSUE TITLE
[vault] permanently uses 1 cpu

### ISSUE THREAD

**Issue by jkleinlercher** [suxess-it/sx-cnp-oss#454]
![image](https://github.com/user-attachments/assets/5fde8232-2bbf-4960-938a-bd4b6fd94679)

**Comment by phac008** [comment]
should be fixed with adaption of sidecar container. there has been a misconfiguration - https://github.com/suxess-it/sx-cnp-oss/commit/4d147fa1e1dcc26e7570c987f75f1e92ed40b3be
