### ISSUE TITLE
[loki] add log dashboard

### ISSUE THREAD

**Issue by phac008** [suxess-it/sx-cnp-oss#60]
automatic deployed dashboards are for loki health only...

examples:
https://grafana.com/grafana/dashboards/?search=loki

**Comment by phac008** [comment]
https://github.com/suxess-it/sx-cnp-oss/commit/7b03ff539c7617c0e2591800e808efb069f77c5d

-> adding and automatic reload (within grafana) works

but...
there is still an issue with "default" datasource on default loki dashboards - default datasource does not contain information - whereas "-- Grafana --" contains information ... investigating

**Comment by phac008** [comment]
additional information:
https://github.com/grafana/loki/issues/9273

**Comment by jkleinlercher** [comment]
And especially this doc https://grafana.com/docs/loki/latest/setup/install/helm/monitor-and-alert/with-local-monitoring/

**Comment by jkleinlercher** [comment]
erster schritt: wie lautet unser CLUSTER_NAME?

The dashboards require certain metric labels to display Kubernetes metrics. The best way to accomplish this is to install the kube-prometheus-stack Helm chart with the following values file, replacing CLUSTER_NAME with the name of your cluster. The cluster name is what you specify during the helm installation, so a cluster installed with the command helm install loki-cluster grafana/loki would be called loki-cluster.

**Comment by jkleinlercher** [comment]
cluster="sx-loki" label is jetzt bei jede menge metriken dabei, d.h. die Konfiguration von https://github.com/suxess-it/sx-cnp-oss/commit/ea185bbe4f60272d50184d33e37cf0bf2524c4a3 scheint gezogen zu haben. Das Dashboard https://grafana-127-0-0-1.nip.io/d/logs/loki-logs?orgId=1&refresh=10s zeigt trtozdem noch keine daten an.

![image](https://github.com/suxess-it/sx-cnp-oss/assets/11465610/92593bd0-46db-416b-b1fb-a88cd2bb27ed)

**Comment by jkleinlercher** [comment]
it seems I face the same issue right now as in https://github.com/grafana/loki/issues/9273#issuecomment-1722289781 

"the loki_build_info metric seems empty on the Prometheus data source."

![image](https://github.com/suxess-it/sx-cnp-oss/assets/11465610/1b8916a6-2d65-4c5b-8c4d-3c46a3b5c64b)

investigating ...

**Comment by jkleinlercher** [comment]
meine Vermutung ist aktuell dass die loki_build_info Metrik nur existiert, wenn selfMonitoring aktiviert ist.
Ist derzeit false: https://github.com/suxess-it/sx-cnp-oss/blob/c41e934bb1b368fa9479fc9e03d8c6cbf27505ad/platform-apps/charts/loki/values-k3d.yaml#L99

Grund: dazu müssten zusätzliche CRDs installiert werden. Lt. Kommentar beim Attribut:

```
    # Self monitoring determines whether Loki should scrape its own logs.
    # This feature currently relies on the Grafana Agent Operator being installed,
    # which is installed by default using the grafana-agent-operator sub-chart.
    # It will create custom resources for GrafanaAgent, LogsInstance, and PodLogs to configure
    # scrape configs to scrape its own logs with the labels expected by the included dashboards.
```

Um den Grafana Agent Operator zu installieren muss man das Helm-Value monitoring.selfMonitoring.grafanaAgent.installOperator auf 'true' setzen, siehe 
 https://github.com/grafana/loki/blob/e39677f97b4ba27c90d9f8d2991441095e55b06e/production/helm/loki/Chart.yaml#L23

Das habe ich jetzt lokal im k3d-Cluster versucht, allerdings taucht da das nächste Problem auf beim syncen:

`CustomResourceDefinition.apiextensions.k8s.io "podlogs.monitoring.grafana.com" is invalid: status.storedVersions[0]: Invalid value: "v1alpha2": must appear in spec.versions`

Meine Vermutung:
es ist schon eine Podlogs CRD über alloy installiert worden mit der Version v1alpha2, und über loki will eine installiert werden mit der Version v1alpha1 und ich vermute deshalb passiert jetzt auch beim syncen von loki der Fehler.



k get crd podlogs.monitoring.grafana.com -n monitoring  -o yaml
```
  names:
    categories:
    - grafana-alloy
    - alloy
    kind: PodLogs
    listKind: PodLogsList
    plural: podlogs
    singular: podlogs
  scope: Namespaced
  versions:
  - name: v1alpha2
```

**Comment by jkleinlercher** [comment]
According to https://grafana.com/docs/agent/latest/flow/reference/components/loki.source.podlogs/ the grafana agent is deprecated so we should use podlogs CRD from alloy which is also newer. Investigating how podlogs instance in Loki could work together with podlogs CRD from alloy (v1alpha1 VS v1alpha2)

**Comment by jkleinlercher** [comment]
> According to https://grafana.com/docs/agent/latest/flow/reference/components/loki.source.podlogs/ the grafana agent is deprecated so we should use podlogs CRD from alloy which is also newer. Investigating how podlogs instance in Loki could work together with podlogs CRD from alloy (v1alpha1 VS v1alpha2)
> 
> ![image](https://private-user-images.githubusercontent.com/11465610/323965211-a7054c35-f882-4628-930f-0cf533c7013e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1Mzc3NDcsIm5iZiI6MTcxMzUzNzQ0NywicGF0aCI6Ii8xMTQ2NTYxMC8zMjM5NjUyMTEtYTcwNTRjMzUtZjg4Mi00NjI4LTkzMGYtMGNmNTMzYzcwMTNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE5VDE0MzcyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjNGRjYzMxNjEwNjZlOGU1MTdkYTQ0NDVhYmRlYmRiZmYwYWJjMDg0YjY3OWI3MjAwMTg2YzMxZjQxZmM3YzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PRdnfUbE1tHw4HM0ms1jBU11zwTB_o1pn-fgN8MokSo)

You can specify the podlogs api version in loki values file https://github.com/grafana/loki/blob/4c563f7823f9f9b7e65026b52e9c16580d4d87f4/production/helm/loki/values.yaml#L3331

**Comment by jkleinlercher** [comment]
Conclusion:

- included dashboards like „Loki logs“ need selfMonitoring enabled. SelfMonitoring needs GrafanaAgent, and GrafanaAgent Podlogs CRD is incompatible with Alloys Podlogs CRD. Still investigating a scenario alloy and Loki selfMonitoring can work together.
- Why „Kubernetes Logs“ dashboard didn‘t work without modifying the datasource variable is still under investigation

**Comment by jkleinlercher** [comment]
> Conclusion:
> 
> * included dashboards like „Loki logs“ need selfMonitoring enabled. SelfMonitoring needs GrafanaAgent, and GrafanaAgent Podlogs CRD is incompatible with Alloys Podlogs CRD. Still investigating a scenario alloy and Loki selfMonitoring can work together. —> [Update loki helm chart to depend on alloy not grafana-agent-operator grafana/loki#12627](https://github.com/grafana/loki/issues/12627)


Let’s try if Loki dashboards and selfmonitoring works when alloy is not installed. If it works, we should think about skipping alloy until it is integrated in Loki instead of grafana agent operator

**Comment by jkleinlercher** [comment]
> Conclusion:
> * Why „Kubernetes Logs“ dashboard didn‘t work without modifying the datasource variable is still under investigation

for this let’s take a look again at the off-the-shelf dashboards https://grafana.com/grafana/dashboards/12611-logging-dashboard-via-loki/
and check how the dazasource settings are there

**Comment by jkleinlercher** [comment]
after uninstalling alloy the loki app with selfMonitoring enabled installs sucessfully (grafanaagent included), however no loki metric is in prometheus datasource.
Also the servicemonitor sx-loki is installed which should scrape the loki metrics (definition in the servicemonitor looks correct and I can scrape prometheus metrics from sx-loki-0 pod sucessfully manually.

```
kubectl get servicemonitor -n monitoring sx-loki
NAME      AGE
sx-loki   2d22h
```

However, the sx-loki servicemonitor doesn't show up in servicediscovery page on prometheus itself:

![image](https://github.com/suxess-it/sx-cnp-oss/assets/11465610/86243a96-e20c-46dd-b256-83cc7c83a4fb)


still investigating ...

**Comment by jkleinlercher** [comment]
when setting `serviceMonitorSelectorNilUsesHelmValues: false ` in the kube-prometheus-stack helm chart we then see in prometheus service discovery also all other servicemonitoris:

![image](https://github.com/suxess-it/sx-cnp-oss/assets/11465610/ed59b002-9f63-4399-ab23-cfeacd16f8cb)

and also the "Loki / logs" Dashboard is now working because the data gets scraped now via the loki serviceMonitor:

![image](https://github.com/suxess-it/sx-cnp-oss/assets/11465610/946621d3-186f-4957-a390-19a740604881)

**Comment by jkleinlercher** [comment]
> > Conclusion:
> > 
> > * Why „Kubernetes Logs“ dashboard didn‘t work without modifying the datasource variable is still under investigation
> 
> for this let’s take a look again at the off-the-shelf dashboards https://grafana.com/grafana/dashboards/15141-kubernetes-service-logs/ and check how the dazasource settings are there

everything as expected. when importing the dashboard from url above you are asked for the datasource uid. since we add it automatically in the helm chart we need to set "loki" as uid also in the configmap https://github.com/suxess-it/sx-cnp-oss/blob/4cfef24243bf187a48fa6c2a74ccfe22aa60aea5/platform-apps/charts/loki/templates/dashboard.yaml#L192

**Comment by jkleinlercher** [comment]
created new k3d cluster and did some tests --> looks good.

One last hint: some self-monitoring dashboards like "[loki-reads resources](https://grafana-127-0-0-1.nip.io/d/reads-resources/loki-reads-resources?orgId=1&refresh=10s)" show no data. 
The reason is, that the query looks for a pod named "loki-read" which doesn't exist in our environment:


`sum by(pod) (rate(container_cpu_usage_seconds_total{cluster=~"$cluster", namespace=~"$namespace", container="loki", pod=~"(loki|enterprise-logs)-read.*"}[$__rate_interval]))`

Maybe some of the dashboards only work for a certain [deployment mode](https://grafana.com/docs/loki/latest/get-started/deployment-modes/]).
