### ISSUE TITLE
deploy order of platform apps

### ISSUE THREAD

**Issue by jkleinlercher** [suxess-it/sx-cnp-oss#74]
kyverno needs servicemonitor, servicemonitor crd gets deployed by kube-prometheus-stack
if kube-prometheus-stack needs more time to deploy, kyverno gets degraded in the meantime

**Comment by phac008** [comment]
additional - certificate generation from e.g. kube-prometheus-stack, grafana need cert-manger in advance

**Comment by jkleinlercher** [comment]
I think the initial argocd Installation already needs the resource customization for app health check

**Comment by jkleinlercher** [comment]
Done for k3d, needs to get done for metalstack

**Comment by jkleinlercher** [comment]
everything looks fine on metalstack and k3d in github action
