### ISSUE TITLE
[backstage] first time accessing docs tab in entity page results in an error

### ISSUE THREAD

**Issue by jkleinlercher** [suxess-it/sx-cnp-oss#90]
after going to docs (left panel) --> entities it also works in the entity page

**Comment by phac008** [comment]
local test:  ok 

in sx-cnp-oss-demo-app techdocs reference found in catalog-info.yaml - (https://github.com/suxess-it/sx-cnp-oss-demo-app/blob/c736cb5563caea08808e43852ed8bd602099de23/catalog-info.yaml#L9) but missing requirements:
...
file mkdocs.yml in root dir & docs dir with referenced files from mkdocs.yml
...

-> added it to sx-cnp-demp-app (https://github.com/suxess-it/sx-cnp-oss-demo-app/commit/3d6668a7f03ee901d210af1a77d7ccaa7c5c6c36 & https://github.com/suxess-it/sx-cnp-oss-demo-app/commit/c736cb5563caea08808e43852ed8bd602099de23)

now works as expected 
---
(Details from Backstage Documentation): https://backstage.io/docs/features/techdocs/creating-and-publishing#enable-documentation-for-an-already-existing-entity)

**Comment by phac008** [comment]
test on metalstack now also ok
