### ISSUE TITLE
[backstage] grafana dashboard in iframe shows no data in the chart, and after some seconds it switchs to argo-rollouts

### ISSUE THREAD

**Issue by jkleinlercher** [suxess-it/sx-cnp-oss#91]
.. this error exists only for entities like https://portal-metalstack.platform-engineer.cloud/catalog/default/component/oo (based on the sX kubevirt Template)

**Comment by phac008** [comment]
first issue is because of wrong namespaces referenced in catalog-info.yaml grafana url, if namespace is missing it will fall back to first namespace in list -> fixed:
https://github.com/suxess-it/sx-cnp-oss/commit/4e2f1b4e35a91777c2080c5e6743a6165f3f0b27

**Comment by jkleinlercher** [comment]
the problem with lacking data is tackled in https://github.com/suxess-it/sx-cnp-oss/issues/53
